// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1:string,arg2:string,arg3:string):Promise<void>;

export function GetInsecureTLS():Promise<boolean>;

export function GetPeerConnected():Promise<boolean>;

export function GetSessionID():Promise<string>;

export function SendCommand(arg1:string):Promise<void>;

export function SetInsecureTLS(arg1:boolean):Promise<void>;
