// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Disconnect() {
  return window['go']['main']['App']['Disconnect']();
}

export function ExecuteCommand(arg1) {
  return window['go']['main']['App']['ExecuteCommand'](arg1);
}

export function GetFrontendICEServers() {
  return window['go']['main']['App']['GetFrontendICEServers']();
}

export function GetInsecureTLS() {
  return window['go']['main']['App']['GetInsecureTLS']();
}

export function GetPeerConnected() {
  return window['go']['main']['App']['GetPeerConnected']();
}

export function GetSessionID() {
  return window['go']['main']['App']['GetSessionID']();
}

export function SetInsecureTLS(arg1) {
  return window['go']['main']['App']['SetInsecureTLS'](arg1);
}
