// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Connect(arg1, arg2, arg3) {
  return window['go']['main']['App']['Connect'](arg1, arg2, arg3);
}

export function GetInsecureTLS() {
  return window['go']['main']['App']['GetInsecureTLS']();
}

export function GetSessionID() {
  return window['go']['main']['App']['GetSessionID']();
}

export function SendCommand(arg1) {
  return window['go']['main']['App']['SendCommand'](arg1);
}

export function SetInsecureTLS(arg1) {
  return window['go']['main']['App']['SetInsecureTLS'](arg1);
}
