// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Disconnect():Promise<void>;

export function ExecuteCommand(arg1:string):Promise<void>;

export function GetFrontendICEServers():Promise<Array<main.frontendICEServer>>;

export function GetInsecureTLS():Promise<boolean>;

export function GetPeerConnected():Promise<boolean>;

export function GetSessionID():Promise<string>;

export function SetInsecureTLS(arg1:boolean):Promise<void>;
